Interpase:
    TextInput:
        id:textinput
        size_hint:0.5,0.1
        pos_hint:{'center_x':0.5,'center_y':0.6}
    Label:
        id:label
        text:'Hi..!'
        size_hint:0.5,0.1
        pos_hint:{'center_x':0.5,'center_y':0.5}
        maltiline:True
    Button:
        id:btn
        text:'Click Me'
        size_hint:0.5,0.1
        pos_hint:{'center_x':0.5,'center_y':0.4}
        on_press:root.Display()

